runtime: python311

env_variables:
  HOST: "0.0.0.0"
  PORT: "5000"

entrypoint: python run.py

automatic_scaling:
  min_instances: 1
  max_instances: 10

health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 1

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 1
  app_start_timeout_sec: 300